server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_solo_bodo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
#    generate-ddl: false
    hibernate:
          generate_statistics: false
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  #    hibernate:
  #      ddl-auto: validate


